Encode user info when setting it
elastic/elastic-transport-php pull request #7
Opened 2022-06-29 13:21 UTC by hamzamogni

This will urlencode user info (username & password) before setting them.

This will make sure passwords with special characters like '@' not cause
problems.

fixes
[https://github.com/elastic/elasticsearch-php/issues/1232](https://github.com/elastic/elasticsearch-php/issues/1232#)

2022-06-30 09:05 UTC, ezimuel requested changes
I leave just a comment for the usage of isset() before using user and password.

2022-06-30 11:11 UTC, ezimuel commented
@hamzamogni I just tested with Guzzle and Nyholm\Psr7 libraries:
```php
require 'vendor/autoload.php';

$user = 'foo@';
$password = 'pass';

$request = new \GuzzleHttp\Psr7\Request('GET', 'http://localhost:9200');
$request = $request->withUri($request->getUri()->withUserInfo($user, $password));

printf("Guzzle: %s\n", $request->getUri()->getUserInfo());

$request = new \Nyholm\Psr7\Request('GET', 'http://localhost:9200');
$request = $request->withUri($request->getUri()->withUserInfo($user, $password));

printf("Nyholm: %s\n", $request->getUri()->getUserInfo());
```
[Guzzle\Psr7](https://github.com/guzzle/psr7) encodes the username correctly using `foo%40` but [Nyholm\Psr7](https://github.com/Nyholm/psr7) does not, leaving the password as is `foo@`.

2022-08-11 14:48 UTC, ezimuel commented
@hamzamogni I just sent this PR https://github.com/Nyholm/psr7/pull/202 to fix the issue in `nyholm/psr7`. In the meantime, I was thinking to set `Guzzle` as default HTTP client in `elasticsearch-php`. This will solve this issue and also others related to the `autodiscovery` usage of HTTPlug.

2022-08-11 15:20 UTC, hamzamogni commented
Hey @ezimuel I just checked your PR, thank you for addressing this. Yes, I think that setting ```Guzzle``` would be a good way to move forward and fix this.

2022-08-11 16:35 UTC, closed without merging